### ISSUE TITLE
Only a single Column and no square icons present on Clean Bookmarks 'mod'

### ISSUE THREAD

**Issue by gatlanit** [CMD-Golem/Zen-Browser-Mods#1]
I'm coming from [your comment on reddit here](https://www.reddit.com/r/zen_browser/comments/1ip744c/comment/mct92b9/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) and I noticed someone had a similar issue that I'm having using the clean bookmarks mod. Specifically, I am seeing only one column and my bookmarks aren't truncated into the 'square icons' properly. There is also a noticeable amount of padding on the right of the bookmarks as well. Though I am also a new user of the Zen Browser so it could very well be an error on my end.

My setup:
- Single toolbar
- Show bookmarks toolbar
- Other Zen Mods (in case they are important)
    - Better Active Tab (v1.0.3)
    - Cleaned URL bar (v1.0.2)
    - Floating Status Bar (v1.0.0)
    - Load Bar (v1.0.0)
    - Now playing indicator (v1.2.1)
    - Pimp your PiP (v1.0.0)
    - Private Mode Highlighting (v1.0.4)
    - Quietify (v1.1.0)
    - SuperPins (v1.4.2)
- I'm using this mod by creating a userChrome.css file under the chrome directory of my profile and pasting the following into it: 

```CSS
/* Remove default styles */
#personal-bookmarks {
	padding: 0 !important;
}
#personal-bookmarks:hover {
	background-color: transparent !important;
}
.toolbarbutton-text[value=""] {
	display: none !important;
}


/* Warp Bookmarks */
#PlacesToolbarItems {
	display: grid;
	grid-template-columns: repeat(3, 1fr); /* Number of columns */
}

/* Horizontal line */
#PlacesToolbar {
	flex-direction: column;
}

#PlacesToolbar:after {
	content: '';
	width: calc(100% - 3px);
	height: 1px;
	margin-top: 5px;
	margin-bottom: 8px;
	display: block;
	height: 1px;
	background: light-dark(rgba(1, 1, 1, 0.075), rgba(255, 255, 255, 0.1));
}

/* Style Bookmark items */
toolbarbutton.bookmark-item:not(.subviewbutton):not(#bookmarks-toolbar-placeholder) {
	height: 36px !important;
	width: calc(100% -1px) !important;
	background-color: var(--tab-hover-background-color) !important;
}
toolbarbutton.bookmark-item:not(.subviewbutton):not(#bookmarks-toolbar-placeholder) image {
	width: 18px !important;
	height: 18px !important;
}
toolbarbutton.bookmark-item:not(.subviewbutton):not(#bookmarks-toolbar-placeholder):hover {
	background-color: var(--tab-selected-bgcolor) !important;
}

/* Expand bookmarks with text */
toolbarbutton.bookmark-item:not(.subviewbutton):not(#bookmarks-toolbar-placeholder):not([label=""]) {
	grid-column-start: 1;
	grid-column-end: 3;
}
toolbarbutton.bookmark-item:not(.subviewbutton):not(#bookmarks-toolbar-placeholder):not([label=""]) image {
	margin-left: 5px;
	margin-right: 5.5px !important;;
}

/* Hide open all in tabs*/
.bookmarks-actions-menuseparator, .openintabs-menuitem {
	display: none;
}
```

This is what it looks like for me when using the mod. 

<img width="230" alt="Image" src="https://github.com/user-attachments/assets/86a49041-8d68-4840-8e40-dbde3c345b37" />

**Comment by gatlanit** [comment]
I was able to make it somewhat better by setting
```CSS
/* Expand bookmarks with text */
toolbarbutton.bookmark-item:not(.subviewbutton):not(#bookmarks-toolbar-placeholder):not([label=""]) {
	grid-column-start: 1;
	grid-column-end: 3;
}
```
to

```CSS
/* Expand bookmarks with text */
toolbarbutton.bookmark-item:not(.subviewbutton):not(#bookmarks-toolbar-placeholder):not([label=""]) {
	grid-column-start: auto;
	grid-column-end: auto;
}
```

as well as columns to
```CSS
/* Warp Bookmarks */
#PlacesToolbarItems {
	display: grid;
	grid-template-columns: repeat(2, 1fr); /* Number of columns */
}
```
(3 columns became too wide)

This is what it looks like now, not perfect but it's more acceptable than what I was getting before...
<img width="306" alt="Image" src="https://github.com/user-attachments/assets/ee0d5bee-63cb-4045-b1bc-a70d3f968422" />

I still want a way to make the width smaller of each of those icons as well as truncate non folder icons to just square icons just like in the [README.md image](https://github.com/CMD-Golem/Zen-Browser-Mods/blob/main/assets/clean-bookmarks.png)

---

**Edit**: So it seems that you need to set your bookmark name to nothing in order to get the "square" icon and you also need to rearrange things in order to make it look coherent in your sidebar. This is now what it looks like after all my edits (original unmodified css) Though my modified one may still be useful for a simpler and easier to setup bookmarks section:

<img width="422" alt="Image" src="https://github.com/user-attachments/assets/66abcabc-46de-4887-b5a8-872d9ecd8512" />
